language: ruby
rvm:
 - 2.3.5

bundler_args: --without production

services:
  - postgresql
  - elasticsearch

before_script:
  - psql -c 'create database peoplefinder_test;' -U postgres
  - bundle exec rake db:migrate

notifications:
  on_success: never
  on_failure: never

env:
  PROFILE_API_TOKEN: BOB
  SUPPORT_EMAIL: support@example.com
